import assert from 'node:assert/strict';
import { CALIBRATION, FIXED_DT } from '../public/src/config.js';
import { DocDonkeysParityPhysics, applyStaticContactResponse } from '../public/src/physics/docdonkeys-parity.js';
const state={gameOver:false}, input={down:{left:false,right:false,launch:false}};
const near=(a,b,t,msg)=>assert(Math.abs(a-b)<=t,`${msg}: ${a} vs ${b}`);

// Static oblique wall impact: reference generated by the exact vendored Box2D 2.3.2.
let ball={vx:150,vy:340.833333333,omega:0,r:9};
applyStaticContactResponse(ball,{x:0,y:-1},0,.2);
near(ball.vx,CALIBRATION.referenceHarness.wallImpact.vx,1.2,'wall vx');
near(ball.vy,CALIBRATION.referenceHarness.wallImpact.vy,.05,'wall vy');
near(ball.omega,CALIBRATION.referenceHarness.wallImpact.omega,.08,'wall spin');
ball={vx:0,vy:340.833333333,omega:0,r:9};applyStaticContactResponse(ball,{x:0,y:-1},1.75,.2);near(ball.vy,CALIBRATION.referenceHarness.bigBumperVy,.05,'big bumper restitution');
ball={vx:0,vy:340.833333333,omega:0,r:9};applyStaticContactResponse(ball,{x:0,y:-1},4,.2);near(ball.vy,CALIBRATION.referenceHarness.leftKickerVy,.05,'left kicker restitution');

// Flipper motor traces. Inputs are delayed by one physics frame exactly like Application::Update.
let p=new DocDonkeysParityPhysics(), trace=[];
for(let f=0;f<30;f++){input.down.left=f>=5&&f<15;input.down.right=false;input.down.launch=false;p.update(FIXED_DT,input,state,{});trace.push({a:p.flippers.left.angle*180/Math.PI,w:p.flippers.left.omega});}
near(trace[6].a,CALIBRATION.referenceHarness.leftFlipperPressFrame1.angleDeg,.2,'left flipper first angle');near(trace[6].w,CALIBRATION.referenceHarness.leftFlipperPressFrame1.omega,.03,'left flipper first omega');near(trace[7].a,CALIBRATION.referenceHarness.leftFlipperPressFrame2.angleDeg,.8,'left flipper second angle');near(trace[14].a,CALIBRATION.referenceHarness.leftFlipperSettledDeg,.02,'left lower slop');near(trace[29].a,2,.02,'left upper slop');

p=new DocDonkeysParityPhysics();trace=[];
for(let f=0;f<30;f++){input.down.left=false;input.down.right=f>=5&&f<15;p.update(FIXED_DT,input,state,{});trace.push({a:p.flippers.right.angle*180/Math.PI,w:p.flippers.right.omega});}
near(trace[6].a,CALIBRATION.referenceHarness.rightFlipperPressFrame1.angleDeg,.3,'right flipper first angle');near(trace[6].w,CALIBRATION.referenceHarness.rightFlipperPressFrame1.omega,.03,'right flipper first omega');near(trace[7].a,CALIBRATION.referenceHarness.rightFlipperPressFrame2.angleDeg,1.0,'right flipper second angle');near(trace[14].a,CALIBRATION.referenceHarness.rightFlipperFullTableHeldStopDeg,.03,'right full-table held stop');near(trace[29].a,-2,.25,'right lower slop');

// Kicker motor alone: matches the negative-max-force Box2D quirk byte-for-behaviour.
p=new DocDonkeysParityPhysics();p.ball.active=false;let samples={};
for(let f=0;f<91;f++){input.down.right=false;input.down.launch=f>=30&&f<60;p.update(FIXED_DT,input,state,{});if([29,31,55,62].includes(f))samples[f]={y:p.kicker.y,vy:p.kicker.vy};}
near(samples[29].y,CALIBRATION.referenceHarness.kickerTopY,.02,'kicker top');near(samples[31].vy,CALIBRATION.referenceHarness.kickerFirstHeldVy,.02,'kicker held acceleration');near(samples[55].y,CALIBRATION.referenceHarness.kickerBottomY,.02,'kicker bottom');near(samples[62].vy,CALIBRATION.referenceHarness.kickerFirstReturnVy,.03,'kicker return acceleration');

// Full launcher lane: static joint attacher is a real collider in the original.
p=new DocDonkeysParityPhysics();let minVy=0,maxY=-Infinity;input.down.left=input.down.right=false;
for(let f=0;f<180;f++){input.down.launch=f>=50&&f<90;p.update(FIXED_DT,input,state,{onLoseBall:()=>{}});minVy=Math.min(minVy,p.ball.vy);maxY=Math.max(maxY,p.ball.y);}
near(maxY,787.632263,0.5,'launcher resting depth');near(minVy,CALIBRATION.referenceHarness.launcherPeakVy,4,'launcher peak velocity');
console.log('Box2D 2.3.2 calibration: PASS');
