(function(){'use strict';
 const G=globalThis.SpinningTileGame,I18N=globalThis.SpinningTileI18N;
 const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),complete=document.getElementById('complete'),status=document.getElementById('loadStatus'),langBtn=document.getElementById('langBtn'),directionSelect=document.getElementById('directionSelect'),backgroundInput=document.getElementById('backgroundInput'),imageInput=document.getElementById('imageInput'),galleryDialog=document.getElementById('galleryDialog'),galleryGrid=document.getElementById('galleryGrid'),helpDialog=document.getElementById('helpDialog'),creditsDialog=document.getElementById('creditsDialog'),previewDialog=document.getElementById('previewDialog'),previewImage=document.getElementById('previewImage');
 const photos=[['Full-202-Tiger-Swallowtail.jpg','Tiger Swallowtail',[98,114,72]],['Full-24-The-Maroon-Bells.jpg','The Maroon Bells',[104,103,100]],['Full-237-Hanging-Lake.jpg','Hanging Lake',[78,102,68]],['Full-261-Yellow-Flower.jpg','Yellow Flower',[84,95,4]],['Full-266-Cascading-Falls.jpg','Cascading Falls',[77,68,38]],['Full-288-Tennessee-Sunset.jpg','Tennessee Sunset',[82,46,47]],['Full-333-Ladybug-in-the-Field.jpg','Ladybug in the Field',[46,64,9]],['Full-334-Light-of-the-Sky.jpg','Light of the Sky',[102,116,137]],['Full-446-Along-the-Banks.jpg','Along the Banks',[70,67,67]],['Full-454-ONeil-Bridge-in-the-Morning.jpg',"O'Neil Bridge in the Morning",[87,97,109]]];
 let lang='en',image=new Image(),imageSrc='assets/photos/Full-202-Tiger-Swallowtail.jpg',logical=null,geom=null,state=null,viewport=null,background=G.backgroundFromMean(98,114,72),hoverVertex=-1,pressedVertex=-1,activePointer=null,shiftDown=false;
 const cwIcon=new Image(),ccwIcon=new Image();cwIcon.src='assets/icons/cwcursor.png';ccwIcon.src='assets/icons/ccwcursor.png';
 function t(k){return I18N[lang][k]||k;} function applyI18n(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));document.querySelectorAll('[data-i18n-aria]').forEach(e=>e.setAttribute('aria-label',t(e.dataset.i18nAria)));document.querySelectorAll('[data-i18n-alt]').forEach(e=>e.setAttribute('alt',t(e.dataset.i18nAlt)));langBtn.textContent=lang==='en'?'IT':'EN';directionSelect.options[0].textContent=t('clockwise');directionSelect.options[1].textContent=t('counterClockwise');}
 function closeMenus(){document.querySelectorAll('.toolbarMenu[open]').forEach(d=>d.removeAttribute('open'));}document.addEventListener('click',e=>{if(!e.target.closest('.toolbarMenu'))closeMenus();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenus();});document.querySelectorAll('.toolbarMenu').forEach(m=>m.addEventListener('toggle',()=>{if(m.open)document.querySelectorAll('.toolbarMenu').forEach(o=>{if(o!==m)o.removeAttribute('open');});}));
 function resizeCanvas(){const r=canvas.getBoundingClientRect(),dpr=Math.max(1,window.devicePixelRatio||1);canvas.width=Math.max(1,Math.round(r.width*dpr));canvas.height=Math.max(1,Math.round(r.height*dpr));if(logical)viewport=G.computeViewport(r.width,r.height,logical.width,logical.height,16);render();}
 function setBackground(c){background=c;backgroundInput.value=c;render();}
 function loadImage(src,mean=null){status.textContent=t('loading');status.classList.remove('hidden');const next=new Image();next.onload=()=>{image=next;imageSrc=src;const rgb=mean||[128,128,128];background=G.backgroundFromMean(...rgb);backgroundInput.value=background;status.classList.add('hidden');newGame();};next.onerror=()=>{status.textContent=t('imageError');status.classList.remove('hidden');};next.src=src;}
 function newGame(){if(!image.naturalWidth)return;logical=G.fitImage(image.naturalWidth,image.naturalHeight);geom=G.layout(logical.width,logical.height);state=G.mix();hoverVertex=-1;pressedVertex=-1;complete.classList.add('hidden');const r=canvas.getBoundingClientRect();viewport=G.computeViewport(r.width,r.height,logical.width,logical.height,16);render();}
 function hexPath(x,y,w,h){ctx.beginPath();ctx.moveTo(x+w/2,y);ctx.lineTo(x+w,y+h/4);ctx.lineTo(x+w,y+3*h/4);ctx.lineTo(x+w/2,y+h);ctx.lineTo(x,y+3*h/4);ctx.lineTo(x,y+h/4);ctx.closePath();}
 function renderTile(pos){const orig=state.originalIndex[pos],rot=state.rotation[pos],dst=G.tilePosition(geom,pos),src=G.tilePosition(geom,orig);if(!dst||!src)return;const w=geom.tileWidth,h=geom.tileHeight,dcx=dst.x+w/2,dcy=dst.y+h/2,scx=src.x+w/2,scy=src.y+h/2,angle=rot*Math.PI/3;
   ctx.save();hexPath(dst.x,dst.y,w,h);ctx.clip();ctx.translate(dcx,dcy);ctx.scale(1,geom.scaleFactor);ctx.rotate(angle);ctx.scale(1,1/geom.scaleFactor);ctx.drawImage(image,-scx,-scy,logical.width,logical.height);ctx.restore();
   const edge=Math.max(1,1/viewport.scale);ctx.save();ctx.lineWidth=edge;ctx.strokeStyle='rgba(0,0,0,.48)';hexPath(dst.x,dst.y,w,h);ctx.stroke();ctx.translate(edge*.7,edge*.7);ctx.strokeStyle='rgba(255,255,255,.28)';hexPath(dst.x,dst.y,w,h);ctx.stroke();ctx.restore();
 }
 function updateMouseCursor(){if(hoverVertex<0||!state||state.solved){canvas.style.cursor='default';return;}const ccw=shiftDown||Number(directionSelect.value)===G.SPIN_CCW;canvas.style.cursor=`url("assets/icons/${ccw?'ccwcursor':'cwcursor'}.png") 16 16, pointer`;}
 function render(){const cssW=canvas.clientWidth,cssH=canvas.clientHeight,dpr=Math.max(1,window.devicePixelRatio||1);ctx.save();ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle=background;ctx.fillRect(0,0,cssW,cssH);if(!state||!viewport){ctx.restore();return;}ctx.translate(viewport.x,viewport.y);ctx.scale(viewport.scale,viewport.scale);ctx.drawImage(image,0,0,logical.width,logical.height);for(let i=0;i<7;i++)renderTile(i);ctx.restore();if(pressedVertex>=0&&!state.solved){const p=G.vertexPosition(geom,pressedVertex),x=viewport.x+p.x*viewport.scale,y=viewport.y+p.y*viewport.scale,icon=Number(directionSelect.value)===G.SPIN_CCW?ccwIcon:cwIcon;ctx.save();ctx.setTransform(dpr,0,0,dpr,0,0);ctx.beginPath();ctx.arc(x,y,23,0,Math.PI*2);ctx.fillStyle='rgba(15,18,22,.55)';ctx.fill();ctx.lineWidth=2;ctx.strokeStyle='rgba(255,255,255,.85)';ctx.stroke();ctx.drawImage(icon,x-16,y-16,32,32);ctx.restore();}updateMouseCursor();}
 function logicalPoint(e){if(!viewport)return null;const r=canvas.getBoundingClientRect();return G.canvasToLogical(e.clientX-r.left,e.clientY-r.top,viewport);}
 function pointerVertex(e){const p=logicalPoint(e);return p?G.getNearestVertex(geom,p.x,p.y):-1;}
 function currentDirection(e){return e&&e.shiftKey?G.SPIN_CCW:Number(directionSelect.value);}
 function activateVertex(v,dir){if(!state)return;if(state.solved){state=G.mix();complete.classList.add('hidden');render();return;}if(v>=0&&v<6){G.spin(state,v,dir);if(state.solved){complete.classList.remove('hidden');hoverVertex=-1;}render();}}
 canvas.addEventListener('pointermove',e=>{if(e.pointerType&&e.pointerType!=='mouse')return;hoverVertex=state&&!state.solved?pointerVertex(e):-1;updateMouseCursor();});canvas.addEventListener('pointerleave',()=>{hoverVertex=-1;updateMouseCursor();});
 canvas.addEventListener('pointerdown',e=>{if(!state)return;const v=pointerVertex(e);activePointer={id:e.pointerId,x:e.clientX,y:e.clientY,v,dir:currentDirection(e),type:e.pointerType||'mouse'};if(activePointer.type!=='mouse'&&v>=0){pressedVertex=v;render();}try{canvas.setPointerCapture(e.pointerId);}catch{}});canvas.addEventListener('pointerup',e=>{if(!activePointer||activePointer.id!==e.pointerId)return;const moved=Math.hypot(e.clientX-activePointer.x,e.clientY-activePointer.y),v=pointerVertex(e),a=activePointer;activePointer=null;pressedVertex=-1;if(moved<=12&&v===a.v)activateVertex(v,a.dir);else render();});canvas.addEventListener('pointercancel',()=>{activePointer=null;pressedVertex=-1;render();});
 canvas.addEventListener('keydown',e=>{if(!state)return;if(state.solved&&(e.key==='Enter'||e.key===' ')){e.preventDefault();activateVertex(-1,G.SPIN_CW);return;}if(/^[1-6]$/.test(e.key)){e.preventDefault();activateVertex(Number(e.key)-1,currentDirection(e));}});
 document.addEventListener('keydown',e=>{if(e.key==='Shift'){shiftDown=true;updateMouseCursor();}});document.addEventListener('keyup',e=>{if(e.key==='Shift'){shiftDown=false;updateMouseCursor();}});
 document.getElementById('newBtn').addEventListener('click',()=>{newGame();closeMenus();});backgroundInput.addEventListener('input',()=>setBackground(backgroundInput.value));directionSelect.addEventListener('change',()=>{updateMouseCursor();render();closeMenus();});document.getElementById('galleryBtn').addEventListener('click',()=>{galleryDialog.showModal();closeMenus();});document.getElementById('previewBtn').addEventListener('click',()=>{previewImage.src=imageSrc;previewDialog.showModal();closeMenus();});document.getElementById('helpBtn').addEventListener('click',()=>{helpDialog.showModal();closeMenus();});document.getElementById('creditsBtn').addEventListener('click',()=>{creditsDialog.showModal();closeMenus();});document.querySelectorAll('dialog .close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));langBtn.addEventListener('click',()=>{lang=lang==='en'?'it':'en';applyI18n();});imageInput.addEventListener('change',()=>{const f=imageInput.files&&imageInput.files[0];if(!f)return;const r=new FileReader();r.onload=()=>loadImage(String(r.result));r.onerror=()=>{status.textContent=t('imageError');status.classList.remove('hidden');};r.readAsDataURL(f);imageInput.value='';closeMenus();});
 photos.forEach(([file,name,mean])=>{const b=document.createElement('button');b.className='photoChoice';b.type='button';b.innerHTML=`<img src="assets/photos/thumbs/${file}" alt=""><span>${name}</span>`;b.addEventListener('click',()=>{galleryDialog.close();loadImage(`assets/photos/${file}`,mean);});galleryGrid.appendChild(b);});
 window.addEventListener('resize',resizeCanvas);applyI18n();requestAnimationFrame(()=>{resizeCanvas();loadImage(imageSrc,photos[0][2]);});
})();
