import test from 'node:test';import assert from 'node:assert/strict';
import {Game,pieceCells,normalizeSettings} from '../public/js/engine.js';
import {SHAPES} from '../public/js/shapes.js';
const settings={width:10,height:15,enabled:[1,2,3,4],initialSpeed:1};
test('exact original catalog: 27 types, category cardinality, 108 occupancy states',()=>{
 assert.equal(SHAPES.length,27);assert.deepEqual([1,2,3,4,5].map(n=>SHAPES.filter(s=>s.count===n).length),[1,1,2,7,16]);
 for(const s of SHAPES){assert.equal(s.cells.length,4);for(const c of s.cells){assert.equal(c.length,s.count);assert.equal(new Set(c.map(p=>p.join(','))).size,s.count);}}
});
test('settings: historical defaults and independent width/height validation',()=>{let g=new Game({},13);assert.equal(g.settings.width,20);assert.equal(g.settings.height,20);assert.deepEqual(g.settings.enabled,[1,2,3,4]);assert.equal(g.allowedIds().length,11);assert.equal(normalizeSettings({width:0,height:100}).width,10);assert.equal(normalizeSettings({height:100}).height,50);});
test('27 full-turn states match source-derived shape geometry',()=>{for(const s of SHAPES){new Game({width:50,height:50,enabled:[5]},13);for(let rot=0;rot<4;rot++){let p={id:s.id,x:12,y:20,rotation:rot};const mapped=pieceCells(p).map(([x,y])=>[x-12,y-20].join(',')).sort();assert.deepEqual(mapped,s.cells[rot].map(p=>p.join(',')).sort());}}});
test('original generator excludes consecutive duplicates where possible',()=>{let g=new Game(settings,1234);for(let i=0;i<90;i++){let prev=g.current.id;g.board=g.board.map(row=>row.map(()=>0));g.current=null;g.spawn();assert.notEqual(g.current.id,prev);}});
test('one type remains playable by explicitly documented port safety rule',()=>{for(const n of [1,2]){let g=new Game({width:10,height:10,enabled:[n]},99);for(let i=0;i<5;i++){assert.equal(g.current.id,n);g.board=g.board.map(row=>row.map(()=>0));g.spawn();}assert.equal(g.gameOver,false);}});
test('spawn uses center first, then searches right and left',()=>{let g=new Game({width:10,height:10,enabled:[1]},3);g.board[9][5]=1;g.board[9][6]=1;g.spawn();assert.equal(g.current.x,7);});
test('rotation near wall is rejected, rotated states are finite',()=>{let g=new Game({width:10,height:20,enabled:[4]},42);g.current={id:6,x:7,y:10,rotation:0};assert.equal(g.rotate(),false);assert.equal(g.current.rotation,0);g.current.x=4;assert.equal(g.rotate(),true);assert.equal(g.current.rotation,1);});
test('move, boundaries and fixed block collisions',()=>{let g=new Game({width:10,height:15,enabled:[1]},12);g.current={id:1,x:0,y:3,rotation:0};assert.equal(g.move(-1,0),false);assert.equal(g.move(0,-1),true);g.board[1][0]=1;assert.equal(g.move(0,-1),false);});
test('two simultaneous line clears compact correctly and use source-derived scoring',()=>{let g=new Game({width:10,height:15,enabled:[1]},1);g.board[0]=Array(10).fill(2);g.board[1]=Array(10).fill(2);g.board[2][1]=7;g.current={id:1,x:2,y:3,rotation:0};assert.equal(g.land(),2);assert.equal(g.score,40);assert.equal(g.totalLines,2);assert.equal(g.board[0][1],7);assert.equal(g.board[1][2],1);assert.equal(g.gameOver,false);});
test('line clear on empty remainder continues (user-observed, safety path)',()=>{let g=new Game({width:10,height:15,enabled:[1]},1);g.board[0]=Array(10).fill(1);g.board[0][3]=0;g.current={id:1,x:3,y:0,rotation:0};assert.equal(g.land(),1);assert.ok(g.current);assert.equal(g.board.flat().filter(Boolean).length,0);});
test('game-over if every valid top spawn is occupied',()=>{let g=new Game({width:10,height:10,enabled:[1]},2);g.board[9]=Array(10).fill(1);g.spawn();assert.equal(g.gameOver,true);});
test('speed progression on original threshold and capped at ten',()=>{let g=new Game({width:10,height:10,enabled:[1],initialSpeed:1},2);g.board[0]=Array(10).fill(1);g.board[0][2]=0;g.current={id:1,x:2,y:0,rotation:0};g.linesAtLevel=99;g.land();assert.equal(g.speed,2);assert.equal(g.linesAtLevel,0);});
test('json web save restores entire model incl generator, not Windows .sg',()=>{let g=new Game(settings,42);g.move(-1,0);g.tick(60);g.togglePause();const snap=g.snapshot();let h=new Game({},111);h.restore(JSON.parse(JSON.stringify(snap)));assert.deepEqual(h.snapshot(),snap);g.togglePause();h.togglePause();for(let i=0;i<6;i++){g.board=g.board.map(row=>row.map(()=>0));h.board=h.board.map(row=>row.map(()=>0));g.spawn();h.spawn();assert.equal(g.current.id,h.current.id);}});
test('invalid/truncated/malicious save is rejected without mutating state',()=>{let g=new Game(settings,42);let initial=g.snapshot();for(const bad of [{format:'Windows.sg'}, {...initial,board:[[1]]},{...initial,current:{id:0,x:0,y:0,rotation:0}},{...initial,score:-100},{...initial,current:{id:1,x:100,y:100,rotation:0}}]){assert.throws(()=>g.restore(bad));assert.deepEqual(g.snapshot(),initial);}});
test('pause prevents simulation changes',()=>{let g=new Game(settings,11);g.togglePause();let state=g.snapshot();g.tick(1000,{down:true});g.rotate();g.move(1,0);assert.deepEqual(g.snapshot(),state);});
