import com.badlogic.gdx.utils.GdxNativesLoader;import com.badlogic.gdx.math.Vector2;import com.badlogic.gdx.physics.box2d.*;import java.util.*;
/** M9 diagnostic oracle for frame-305 sling:9 multi-contact TOI island. */
public class Sling9Oracle {
 static final float DT=1f/60f,S=CometFullTableOracle.S,X=.256052673f,Y=.568660140f,VX=.084415071f,VY=-1.107105970f,OMEGA=9.860973358f;
 static String lab(Fixture f){Object o=f.getUserData();return o==null?"unlabeled":String.valueOf(o);} static Fixture other(Contact c,Body b){return c.getFixtureA().getBody()==b?c.getFixtureB():c.getFixtureA();}
 static void state(String t,Body b){Vector2 p=b.getPosition(),v=b.getLinearVelocity();System.out.printf(Locale.US,"STATE,%s,%.9f,%.9f,%.9f,%.9f,%.9f%n",t,p.x/S,p.y/S,v.x/S,v.y/S,b.getAngularVelocity());}
 static void run(boolean continuous){final World w=new World(new Vector2(0,CometFullTableOracle.G),true);w.setContinuousPhysics(continuous);CometFullTableOracle.slingshot(w,9,.35f,.54f,0,.08f,-.08f,0);final Body b=CometFullTableOracle.ball(w);b.setTransform(X*S,Y*S,0);b.setLinearVelocity(VX*S,VY*S);b.setAngularVelocity(OMEGA);final int[] q={0};w.setContactListener(new ContactListener(){boolean ours(Contact c){return c.getFixtureA().getBody()==b||c.getFixtureB().getBody()==b;}void out(String k,Contact c){if(!ours(c))return;WorldManifold m=c.getWorldManifold();System.out.printf(Locale.US,"%s,%d,%s,%d,%.9f,%.9f",k,q[0]++,lab(other(c,b)),m.getNumberOfContactPoints(),m.getNormal().x,m.getNormal().y);for(int i=0;i<m.getNumberOfContactPoints();i++)System.out.printf(Locale.US,",%.9f,%.9f",m.getPoints()[i].x/S,m.getPoints()[i].y/S);System.out.println();}public void beginContact(Contact c){out("BEGIN",c);}public void endContact(Contact c){out("END",c);}public void preSolve(Contact c,Manifold m){out("PRE",c);}public void postSolve(Contact c,ContactImpulse i){if(!ours(c))return;WorldManifold m=c.getWorldManifold();float[] ni=i.getNormalImpulses(),ti=i.getTangentImpulses();System.out.printf(Locale.US,"POST,%d,%s,%d,%.9f,%.9f",q[0]++,lab(other(c,b)),i.getCount(),m.getNormal().x,m.getNormal().y);for(int j=0;j<i.getCount();j++)System.out.printf(Locale.US,",%.9f,%.9f,%.9f,%.9f",m.getPoints()[j].x/S,m.getPoints()[j].y/S,ni[j]/S,ti[j]/S);System.out.println();}});state("before",b);w.step(DT,6,2);state("after",b);w.dispose();}
 public static void main(String[] a){GdxNativesLoader.load();run(a.length==0||!a[0].equals("discrete"));}
}
