import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("il restauro standalone usa motore e sprite preservati senza framework", async () => {
  const [html, ui, css, favicon] = await Promise.all([
    readFile(new URL("../public/index.html", import.meta.url), "utf8"),
    readFile(new URL("../public/src/ui.js", import.meta.url), "utf8"),
    readFile(new URL("../public/style.css", import.meta.url), "utf8"),
    readFile(new URL("../public/favicon.svg", import.meta.url), "utf8"),
  ]);
  assert.match(html, /rel="icon" href="\.\/favicon\.svg\?v=44"/);
  assert.match(favicon, /🐽/);
  assert.match(favicon, /#d8ff80/);
  assert.match(html, /href="\.\/style\.css\?v=63"/);
  assert.match(html, /src="\.\/src\/ui\.js\?v=63"/);
  assert.match(html, /data-i18n="readableDeck">Alta leggibilità/);
  assert.match(ui, /readableDeck: "High visibility"/);
  assert.doesNotMatch(`${html}\n${ui}`, /Grandi indici|Large indices/);
  assert.match(html, /value="letele"[^>]*selected/);
  assert.match(html, /id="generation-overlay"/);
  assert.match(html, /id="reset-local-data"/);
  assert.match(html, /id="reset-dialog"/);
  assert.match(html, /id="reset-confirm"/);
  assert.match(html, /id="abandon-dialog"/);
  assert.match(html, /id="abandon-confirm"/);
  assert.match(ui, /storage\.removeItem\(key\)/);
  assert.match(ui, /sessionStorage/);
  assert.match(ui, /caches\.delete\(key\)/);
  assert.match(ui, /registration\.unregister\(\)/);
  assert.match(ui, /location\.replace\(`\.\/index\.html\?reset=\$\{Date\.now\(\)\}`\)/);
  assert.match(ui, /els\.abandonDialog\.showModal\(\)/);
  assert.match(ui, /restartSolvable\(\{ confirmAbandon: false \}\)/);
  assert.doesNotMatch(ui, /confirm\(t\("abandon"\)\)/);
  assert.doesNotMatch(html, /class="provenance"/);
  assert.doesNotMatch(html, /class="menu-meta"|2 reperti MIT \+ 2 mazzi CC0/);
  assert.match(html, /Grugnetto’s Klondike/);
  assert.match(html, /class="brand-badge-content"/);
  assert.doesNotMatch(html, /Il solitario classico, restaurato/);
  assert.doesNotMatch(ui, /The classic solitaire, restored/);
  assert.match(ui, /versione moderna del classico solitario/);
  assert.match(ui, /modern version of the classic solitaire game/);
  assert.doesNotMatch(ui, /due progetti MIT non più sviluppati|two inactive MIT-licensed projects/);
  assert.doesNotMatch(ui, /Il solver verifica|The solver checks/);
  assert.match(html, /id="undo"/);
  assert.match(html, /id="draw-mode"/);
  assert.match(html, /id="draw-indicator"/);
  assert.match(html, /id="menu-toggle"/);
  assert.match(html, /id="language"/);
  assert.match(html, /id="card-deck"/);
  assert.match(html, /value="letele"/);
  assert.match(html, /value="woodcut"/);
  assert.match(html, /data-page="provenance"/);
  assert.match(html, /data-i18n="provenance">Informazioni/);
  assert.match(html, /id="auto-finish"/);
  assert.match(ui, /from "\.\/engine\.js"/);
  assert.match(ui, /from "\.\/sprite\.js"/);
  assert.match(ui, /const HOLD_MS = 200/);
  assert.match(ui, /\(window\.innerWidth - 4\) \/ MOBILE_BASE_WIDTH/);
  assert.match(ui, /shell\.style\.zoom = uiScale/);
  assert.match(ui, /window\.innerHeight - 274/);
  assert.match(ui, /els\.felt\.style\.minHeight = window\.innerWidth <= 720/);
  assert.doesNotMatch(css, /card-arrive/);
  assert.match(css, /\.lab-brand \{ display: flex; align-items: baseline;/);
  assert.match(css, /\.menu-panel \{[^}]*max-height: calc\(100dvh - 76px\)/);
  assert.match(css, /\.menu-panel \{[^}]*overflow-y: auto/);
  assert.match(ui, /drawImage\(spriteImage, sourceX, sourceY, CARD_W, CARD_H/);
  assert.match(ui, /CARD_W \* \(suitRow\[card\.suit\] - 1\)/);
  assert.match(ui, /new Worker\("\.\/src\/solver-worker\.js\?v=21"/);
  assert.match(ui, /localStorage\.setItem\(SOLVED_CACHE/);
  assert.match(ui, /game\.waste\.slice\(-3\)/);
  assert.match(ui, /function preloadDeck\(deck\)/);
  assert.match(ui, /function loadDeckImageOnce\(url\)/);
  assert.match(ui, /attempt < 3/);
  assert.match(ui, /function useReadableDeckFallback/);
  assert.match(ui, /if \(rerender && game\) render\(\)/);
  assert.match(css, /\.card-index \{[^}]*font-size: 23px/);
  assert.match(ui, /new URL\("\.\.\/assets\/decks\/", import\.meta\.url\)/);
  assert.match(ui, /letele\/B-1\.svg/);
  assert.match(css, /\.card\.deck-letele\.face-down, \.card\.deck-woodcut\.face-down \{ background-color: #173f75; \}/);
  assert.match(ui, /generateCertifiedDeal\(drawCount, true\)/);
  assert.match(ui, /let preferredDrawCount = localStorage\.getItem\(DRAW_PREFERENCE\) === "1" \? 1 : 3/);
  assert.match(ui, /const drawCount = preferredDrawCount/);
  assert.match(ui, /localStorage\.setItem\(DRAW_PREFERENCE, String\(preferredDrawCount\)\)/);
  assert.doesNotMatch(ui, /els\.drawMode\.value = String\(currentDrawCount\)/);
  assert.match(ui, /maxAttempts: foreground \? FOREGROUND_BATCH_ATTEMPTS : BACKGROUND_BATCH_ATTEMPTS/);
  assert.doesNotMatch(ui, /SOLVABLE_DEALS|BASE_DEALS/);
  assert.doesNotMatch(ui, /Scarti riciclati senza inversione|come nel sorgente 2017/);
  assert.match(ui, /Gli scarti sono tornati nel tallone/);
  assert.match(ui, /The waste cards are back in the stock/);
  assert.match(ui, /mode: "hint"/);
  assert.doesNotMatch(ui, /react|webpack|babel/i);
});
