#################################
----
-xx-
-xx-
----

-xx-
xxxx
xxxx
-xx-

-xx-
xxxx
xxxx
-xx-

----
-xx-
-xx-
----
#################################
-xx-
xxxx
xxxx
-xx-

xxxx
xxxx
xxxx
xxxx

xxxx
xxxx
xxxx
xxxx

-xx-
xxxx
xxxx
-xx-
#################################
-xx-
xxxx
xxxx
-xx-

xxxx
xxxx
xxxx
xxxx

xxxx
xxxx
xxxx
xxxx

-xx-
xxxx
xxxx
-xx-
#################################
----
-xx-
-xx-
----

-xx-
xxxx
xxxx
-xx-

-xx-
xxxx
xxxx
-xx-

----
-xx-
-xx-
----
#################################
