(function (global) {
  'use strict';
  global.STPI18N = {
    en: {
      gameMenu:'Game', newGame:'New puzzle', puzzleMenu:'Puzzle', gallery:'Gallery', myImage:'My image', size:'Size', preview:'Preview', backgroundColor:'Background', helpMenu:'Help', help:'Instructions', credits:'Credits', changeLanguage:'Change language', gameControls:'Game controls', boardLabel:'Sliding tile puzzle board', boardHint:'Use click or tap. With the keyboard, the arrow keys move the empty space.', choosePicture:'Choose a picture', galleryIntro:'The original collection included these ten photographs.', helpTitle:'How to play', help1:'Rebuild the picture by sliding tiles into the empty space.', help2:'Click or tap a tile next to the empty space. Only adjacent tiles can move.', help3:'Choose 3×3, 4×4 or 5×5 for a different challenge.', help4:'When the picture is complete, click or tap the board to shuffle it again.', help5:'Choose Gallery for one of the original photographs, or My image for a picture from your device.', help6:'Keyboard: the arrow keys move the empty space. Enter or Space shuffles again after completion.', complete:'Puzzle complete! Tap the board to shuffle again.', closeLabel:'Close', restorationCredit:'HTML5 restoration and preservation by', originalCredit:'Original Sliding Tile Puzzle from Virtual Toybox Puzzle Collection © 2010 Jonathan Hulka. GNU GPL v3 or later.', photosCredit:'Photographs ©', licensedUnder:'licensed under', imageError:'This image could not be opened.', loading:'Loading image…', previewTitle:'Picture preview', previewAlt:'Puzzle image preview'
    },
    it: {
      gameMenu:'Partita', newGame:'Nuovo puzzle', puzzleMenu:'Puzzle', gallery:'Galleria', myImage:'Mia immagine', size:'Dimensione', preview:'Anteprima', backgroundColor:'Sfondo', helpMenu:'Aiuto', help:'Istruzioni', credits:'Crediti', changeLanguage:'Cambia lingua', gameControls:'Controlli di gioco', boardLabel:'Tavola dello Sliding Tile Puzzle', boardHint:'Usa clic o tocco. Con la tastiera, le frecce spostano lo spazio vuoto.', choosePicture:'Scegli un’immagine', galleryIntro:'La raccolta originale includeva queste dieci fotografie.', helpTitle:'Come si gioca', help1:'Ricostruisci l’immagine facendo scorrere le tessere nello spazio vuoto.', help2:'Fai clic o tocca una tessera accanto allo spazio vuoto. Possono muoversi solo le tessere adiacenti.', help3:'Scegli 3×3, 4×4 o 5×5 per cambiare difficoltà.', help4:'Quando l’immagine è completa, fai clic o tocca il tavolo per mescolarla di nuovo.', help5:'Scegli Galleria per una delle fotografie originali, oppure Mia immagine per una foto dal tuo dispositivo.', help6:'Tastiera: le frecce spostano lo spazio vuoto. Invio o Spazio rimescolano dopo il completamento.', complete:'Puzzle completato! Tocca il tavolo per mescolare di nuovo.', closeLabel:'Chiudi', restorationCredit:'Restauro e preservazione HTML5 di', originalCredit:'Sliding Tile Puzzle originale da Virtual Toybox Puzzle Collection © 2010 Jonathan Hulka. GNU GPL v3 o successiva.', photosCredit:'Fotografie ©', licensedUnder:'distribuite con licenza', imageError:'Impossibile aprire questa immagine.', loading:'Caricamento immagine…', previewTitle:'Anteprima immagine', previewAlt:'Anteprima dell’immagine del puzzle'
    }
  };
})(typeof globalThis !== 'undefined' ? globalThis : this);
