'use strict';
const assert=require('node:assert/strict');
const {create,target}=require('../public/js/camera');
const W=.76,H=1.40;
const at=(x,y,vx=0,vy=0)=>({x,y,vx,vy});
const cam=create(W,H);
cam.snap(at(.74,.02));
const bottom=cam.transform(456,840);
assert.ok(bottom.sx(.74)>0&&bottom.sx(.74)<456,'launch-lane ball remains visible');
assert.ok(bottom.sy(.02)>0&&bottom.sy(.02)<840,'bottom ball remains visible');
cam.update(at(.35,1.30,0,.75),.1);
for(let i=0;i<30;i++)cam.update(at(.35,1.30,0,.75),1/60);
const top=cam.transform(456,840);
assert.ok(top.sy(1.30)>0&&top.sy(1.30)<840,'top ball remains visible');
assert.ok(top.ty!==bottom.ty,'camera physically moves in vertical axis');
assert.ok(Math.abs(top.scaleX-bottom.scaleX)<1e-9,'zoom is fixed while following');
cam.setFollowing(false,at(.35,1.30));
const full=cam.transform(456,840);
assert.equal(full.sx(0),0);assert.equal(full.sx(W),456);assert.equal(full.sy(0),840);assert.equal(full.sy(H),0);
assert.equal(full.scaleX,456/W);
cam.setFollowing(true,at(.74,.02));
assert.ok(cam.transform(456,840).sx(.74)<=456);
assert.ok(target(at(-100,100),W,H,1.75).x>=0);
console.log('PASS camera: follows ball horizontally/vertically; ball remains visible; overview covers entire original table');
