const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');const P=require('../public/js/physics.js');
global.window={};vm.runInThisContext(fs.readFileSync(path.join(__dirname,'../public/data/playfield.js'),'utf8'));
const e=new P.Engine(window.COMET_PLAYFIELD),b=P.makeBall(),DT=1/60;
const before={x:.437566608,y:.510228634,vx:-1.218472242,vy:.267061323,omega:20.670352936};
const native={normal:{x:.707106769,y:-.707106769},prePoint:{x:.412793726,y:.522440195},postPoint:{x:.412961662,y:.520379424},normalImpulse:.740516722,tangentImpulse:-.150453821,after:{x:.423091650,y:.510249496,vx:.156965286,vy:-.663775146,omega:-27.062618256}};
Object.assign(b,before);const sweep={c0x:b.x,c0y:b.y};b.vy+=P.constants.G*DT;sweep.c1x=b.x+b.vx*DT;sweep.c1y=b.y+b.vy*DT;b.x=sweep.c1x;b.y=sweep.c1y;
const toi=P.helpers.solveBallPolygonTOI(b,e.obstacle8,sweep,DT,{scaledFloatPosition:true});assert(toi,'obstacle:8 TOI missing');const d=(a,c)=>Math.hypot(a.x-c.x,a.y-c.y);
assert(toi.positionIterations===3,'obstacle:8 must take the historical third float32 TOI position iteration');assert(d(toi.normal,native.normal)<1e-6,'obstacle:8 normal diverged');assert(d(toi.pre.points[0],native.prePoint)<1e-6,'obstacle:8 pre point diverged');assert(d(toi.post.points[0],native.postPoint)<1e-6,'obstacle:8 post point diverged');assert(Math.abs(toi.normalImpulse-native.normalImpulse)<1e-6,'obstacle:8 normal impulse diverged');assert(Math.abs(toi.tangentImpulse-native.tangentImpulse)<1e-6,'obstacle:8 tangent impulse diverged');
const positionError=d(b,native.after),velocityError=Math.hypot(b.vx-native.after.vx,b.vy-native.after.vy),omegaError=Math.abs(b.omega-native.after.omega);assert(positionError<2e-7,`obstacle:8 position error ${positionError}`);assert(velocityError<3e-6,`obstacle:8 velocity error ${velocityError}`);assert(omegaError<1e-4,`obstacle:8 omega error ${omegaError}`);console.log('M9 obstacle:8 float32 TOI parity passed');console.log(JSON.stringify({alpha:toi.alpha,positionIterations:toi.positionIterations,normalImpulse:toi.normalImpulse,tangentImpulse:toi.tangentImpulse,positionError,velocityError,omegaError},null,2));
