import{applyLanguage,STRINGS}from'./i18n.js';
import{createSquareGeometry,createHexGeometry,makeRng,rotateVectorSteps}from'./geometry2012.js';
import{collectSnapCandidates,planSnap2012,SNAP_THRESHOLD}from'./snapping.js';
import{LAYER_COUNT,visiblePieces,moveGroupsToLayer,normalizeRect,rectsIntersect}from'./layers.js';
import{createSaveData,parseSaveText,stringifySaveData}from'./savegame.js';
import{planSolvedPlacement}from'./completion.js';
import{computeViewport,canvasToPlayfield}from'./viewport.js';

const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),newBtn=document.querySelector('#newBtn'),saveBtn=document.querySelector('#saveBtn'),saveInput=document.querySelector('#saveInput'),galleryBtn=document.querySelector('#galleryBtn'),galleryDialog=document.querySelector('#galleryDialog'),galleryGrid=document.querySelector('#galleryGrid'),imageInput=document.querySelector('#imageInput'),pieceCount=document.querySelector('#pieceCount'),shapeSelect=document.querySelector('#shapeSelect'),layerSelect=document.querySelector('#layerSelect'),langBtn=document.querySelector('#langBtn'),complete=document.querySelector('#complete'),loadStatus=document.querySelector('#loadStatus');
const PHOTOS=[
 ['Full-202-Tiger-Swallowtail.jpg','Tiger Swallowtail'],
 ['Full-24-The-Maroon-Bells.jpg','The Maroon Bells'],
 ['Full-237-Hanging-Lake.jpg','Hanging Lake'],
 ['Full-261-Yellow-Flower.jpg','Yellow Flower'],
 ['Full-266-Cascading-Falls.jpg','Cascading Falls'],
 ['Full-288-Tennessee-Sunset.jpg','Tennessee Sunset'],
 ['Full-333-Ladybug-in-the-Field.jpg','Ladybug in the Field'],
 ['Full-334-Light-of-the-Sky.jpg','Light of the Sky'],
 ['Full-446-Along-the-Banks.jpg','Along the Banks'],
 ['Full-454-ONeil-Bridge-in-the-Morning.jpg',"O'Neil Bridge in the Morning"]
];
let lang=(['en','it'].includes(readPref('lang','en'))?readPref('lang','en'):'en'),image=new Image(),currentImage={kind:'gallery',file:PHOTOS[0][0],title:PHOTOS[0][1]},imageURL=assetUrl('assets/photos/'+PHOTOS[0][0]),geom,pieces=[],drag=null,dpr=1,boardImage=document.createElement('canvas'),seed=Date.now()>>>0,currentLayer=0,selectedGroups=new Set(),gameComplete=false,playfield={width:0,height:0},viewport={scale:1,offsetX:0,offsetY:0};
const SNAP=SNAP_THRESHOLD;

function assetUrl(path){return new URL(path,document.baseURI).href;}
function readPref(key,fallback){try{return localStorage.getItem('libreJigsaw.'+key)||fallback}catch{return fallback}}
function savePref(key,value){try{localStorage.setItem('libreJigsaw.'+key,String(value))}catch{}}
function createGeometryForBoard(boardWidth,boardHeight){const count=Number(pieceCount.value),g=shapeSelect.value==='hex'?createHexGeometry(boardWidth,boardHeight,count,seed):createSquareGeometry(boardWidth,boardHeight,count,seed);g.boardWidth=boardWidth;g.boardHeight=boardHeight;return g;}
function createGeometryForPlayfield(){const fit=fitImageRect(playfield.width,playfield.height,image.naturalWidth,image.naturalHeight);return createGeometryForBoard(fit.w,fit.h);}
function updateViewport(){const cw=canvas.clientWidth,ch=canvas.clientHeight;if(playfield.width>0&&playfield.height>0&&cw>0&&ch>0){viewport=computeViewport(cw,ch,playfield.width,playfield.height);}else{viewport={scale:1,offsetX:0,offsetY:0};if(playfield.width>0&&playfield.height>0&&(cw===0||ch===0))requestAnimationFrame(()=>{updateViewport();draw();});}}
function resize(){const r=canvas.getBoundingClientRect();dpr=Math.max(1,window.devicePixelRatio||1);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);if(image.complete&&image.naturalWidth&&!pieces.length)newGame(false);updateViewport();draw();}
function fitImageRect(w,h,iw,ih){const pad=Math.max(18,Math.min(w,h)*.06),maxW=w-pad*2,maxH=h-pad*2,s=Math.min(maxW/iw,maxH/ih,.95);return{w:Math.max(140,Math.floor(iw*s)),h:Math.max(105,Math.floor(ih*s))};}
function rebuildImage(){boardImage.width=geom.boardWidth||1;boardImage.height=geom.boardHeight||1;const g=boardImage.getContext('2d');g.clearRect(0,0,boardImage.width,boardImage.height);g.drawImage(image,0,0,boardImage.width,boardImage.height);}
function newGame(bump=true){if(!image.naturalWidth)return;if(bump)seed=randomSeed();playfield={width:Math.max(1,canvas.clientWidth),height:Math.max(1,canvas.clientHeight)};geom=createGeometryForPlayfield();rebuildImage();const w=playfield.width,h=playfield.height,rng=makeRng(seed^0x9e3779b9),margin=Math.max(geom.tileWidth,geom.tileHeight)*.25;pieces=geom.tiles.map((t,i)=>({...t,x:margin+rng()*Math.max(1,w-geom.tileWidth-margin*2),y:margin+rng()*Math.max(1,h-geom.tileHeight-margin*2),rotation:Math.floor(rng()*geom.rotationSteps),group:i,z:i,layer:0}));shuffle(pieces,rng);pieces.forEach((p,i)=>p.z=i);currentLayer=0;layerSelect.value='0';selectedGroups.clear();drag=null;gameComplete=false;complete.classList.add('hidden');updateViewport();draw();}
function randomSeed(){try{return crypto.getRandomValues(new Uint32Array(1))[0]>>>0}catch{return(Math.random()*0xffffffff)>>>0}}
function shuffle(a,rng){for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}}
function groupOf(id){return pieces.filter(p=>p.group===id);}
function bringGroupTop(id){const g=groupOf(id),s=new Set(g);pieces=[...pieces.filter(p=>!s.has(p)),...g];pieces.forEach((p,i)=>p.z=i);}
function bringGroupsTop(groups){const s=new Set(groups),top=pieces.filter(p=>s.has(p.group));pieces=[...pieces.filter(p=>!s.has(p.group)),...top];pieces.forEach((p,i)=>p.z=i);}
function stepAngle(rotation){return rotation*Math.PI*2/geom.rotationSteps;}
function localPoint(p,x,y){const cx=p.x+geom.tileWidth/2,cy=p.y+geom.tileHeight/2,a=-stepAngle(p.rotation),dx=x-cx,dy=y-cy,c=Math.cos(a),s=Math.sin(a);return{x:dx*c-dy*s+geom.tileWidth/2,y:dx*s+dy*c+geom.tileHeight/2};}
function hit(x,y){for(let i=pieces.length-1;i>=0;i--){const p=pieces[i];if(p.layer!==currentLayer)continue;const q=localPoint(p,x,y);if(ctx.isPointInPath(p.path,q.x,q.y))return p;}return null;}
function drawPiece(p){ctx.save();ctx.translate(p.x+geom.tileWidth/2,p.y+geom.tileHeight/2);ctx.rotate(stepAngle(p.rotation));ctx.translate(-geom.tileWidth/2,-geom.tileHeight/2);ctx.save();ctx.clip(p.path);ctx.drawImage(boardImage,-p.origX,-p.origY);if(selectedGroups.has(p.group)){ctx.fillStyle='rgba(70,190,255,.22)';ctx.fillRect(0,0,geom.tileWidth,geom.tileHeight);}ctx.restore();ctx.lineWidth=selectedGroups.has(p.group)?2:1;ctx.strokeStyle=selectedGroups.has(p.group)?'rgba(120,220,255,.95)':'rgba(0,0,0,.58)';ctx.stroke(p.path);ctx.restore();}
function drawMarquee(){if(!drag||drag.mode!=='marquee')return;const r=normalizeRect(drag.start,drag.last);ctx.save();ctx.setLineDash([7,5]);ctx.lineWidth=1.5;ctx.strokeStyle='rgba(150,225,255,.95)';ctx.fillStyle='rgba(90,180,230,.12)';ctx.fillRect(r.x,r.y,r.w,r.h);ctx.strokeRect(r.x+.5,r.y+.5,r.w,r.h);ctx.restore();}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.setTransform(dpr*viewport.scale,0,0,dpr*viewport.scale,dpr*viewport.offsetX,dpr*viewport.offsetY);for(const p of pieces)if(p.layer===currentLayer)drawPiece(p);drawMarquee();}
function pos(e){const r=canvas.getBoundingClientRect(),q=canvasToPlayfield(e.clientX-r.left,e.clientY-r.top,viewport);return q;}
function moveGroup(id,dx,dy){for(const p of groupOf(id)){p.x+=dx;p.y+=dy;}}
function moveGroups(groups,dx,dy){for(const id of groups)moveGroup(id,dx,dy);}
function rotateGroupSteps(anchor,steps){const g=groupOf(anchor.group),cx=anchor.x+geom.tileWidth/2,cy=anchor.y+geom.tileHeight/2;for(const p of g){const pcx=p.x+geom.tileWidth/2,pcy=p.y+geom.tileHeight/2,v=rotateVectorSteps(pcx-cx,pcy-cy,steps,geom.rotationSteps);p.x=cx+v.x-geom.tileWidth/2;p.y=cy+v.y-geom.tileHeight/2;p.rotation=(p.rotation+steps%geom.rotationSteps+geom.rotationSteps)%geom.rotationSteps;}}
function rotateGroup(anchor,dir){rotateGroupSteps(anchor,dir);draw();}
function centerSolvedGroup(groupId,normalizeRotation=true){const g=groupOf(groupId);if(!g.length)return;const initial=planSolvedPlacement(g[0],geom,playfield.width,playfield.height);if(normalizeRotation&&initial.normalizeSteps)rotateGroupSteps(g[0],initial.normalizeSteps);const anchor=groupOf(groupId)[0],plan=planSolvedPlacement(anchor,geom,playfield.width,playfield.height);moveGroup(groupId,plan.dx,plan.dy);currentLayer=anchor.layer;layerSelect.value=String(currentLayer);}
function finishGame(groupId){centerSolvedGroup(groupId,true);selectedGroups.clear();drag=null;gameComplete=true;complete.classList.remove('hidden');draw();}
function trySnap(groupId){const active=visiblePieces(pieces,currentLayer),movingSize=groupOf(groupId).length,candidates=collectSnapCandidates(active,groupId,geom,SNAP),plan=planSnap2012(movingSize,candidates);if(!plan)return false;moveGroup(groupId,plan.moving.dx,plan.moving.dy);for(const c of candidates){const d=plan.external.get(c.group);if(d)moveGroup(c.group,d.dx,d.dy);}const merged=new Set(candidates.map(c=>c.group));for(const p of pieces)if(merged.has(p.group))p.group=groupId;if(groupOf(groupId).length===pieces.length)finishGame(groupId);return true;}
function clearSelection(){selectedGroups.clear();}
function rotatedBounds(p){const cx=p.x+geom.tileWidth/2,cy=p.y+geom.tileHeight/2,a=stepAngle(p.rotation),c=Math.cos(a),s=Math.sin(a),pts=[[p.x,p.y],[p.x+geom.tileWidth,p.y],[p.x+geom.tileWidth,p.y+geom.tileHeight],[p.x,p.y+geom.tileHeight]].map(([x,y])=>{const dx=x-cx,dy=y-cy;return{x:cx+dx*c-dy*s,y:cy+dx*s+dy*c};});const xs=pts.map(q=>q.x),ys=pts.map(q=>q.y);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)};}
function pieceIntersectsRect(p,r){const b=rotatedBounds(p);if(!rectsIntersect(b,r))return false;const ix0=Math.max(b.x,r.x),iy0=Math.max(b.y,r.y),ix1=Math.min(b.x+b.w,r.x+r.w),iy1=Math.min(b.y+b.h,r.y+r.h);if(ix1<ix0||iy1<iy0)return false;const steps=6;for(let yi=0;yi<=steps;yi++)for(let xi=0;xi<=steps;xi++){const x=ix0+(ix1-ix0)*xi/steps,y=iy0+(iy1-iy0)*yi/steps,q=localPoint(p,x,y);if(ctx.isPointInPath(p.path,q.x,q.y))return true;}return false;}
function setSelection(r){const groups=new Set();for(let i=pieces.length-1;i>=0;i--){const p=pieces[i];if(p.layer===currentLayer&&pieceIntersectsRect(p,r))groups.add(p.group);}selectedGroups=groups;if(groups.size)bringGroupsTop(groups);}
function switchLayer(layer){if(gameComplete)return;const next=Math.max(0,Math.min(LAYER_COUNT-1,Number(layer)||0));let transfer=new Set();if(drag?.mode==='group')transfer.add(drag.group);else if(drag?.mode==='selection')transfer=new Set(drag.groups);else if(selectedGroups.size)transfer=new Set(selectedGroups);if(transfer.size)moveGroupsToLayer(pieces,transfer,next);currentLayer=next;layerSelect.value=String(next);draw();}
function setLoadStatus(key=''){if(!loadStatus)return;loadStatus.dataset.statusKey=key;const text=key?(STRINGS[lang]?.[key]||key):'';loadStatus.textContent=text;loadStatus.classList.toggle('hidden',!text);}
function setImageSource(src,meta,onReady){setLoadStatus('loadingImage');const next=new Image();next.decoding='async';next.onload=()=>{image=next;imageURL=src;if(meta)currentImage=meta;setLoadStatus('');if(onReady){try{onReady();}catch{setLoadStatus('saveLoadError');}}else newGame(true);};next.onerror=()=>setLoadStatus('imageLoadError');next.src=src;}
function loadUserImage(file){if(!file)return;setLoadStatus('loadingImage');const reader=new FileReader();reader.onerror=()=>setLoadStatus('imageLoadError');reader.onload=()=>{const data=String(reader.result);setImageSource(data,{kind:'embedded',name:file.name||'image',mime:file.type||'image/*',data});};reader.readAsDataURL(file);}
function buildGallery(){galleryGrid.replaceChildren();for(const [file,title] of PHOTOS){const b=document.createElement('button');b.type='button';b.className='photoChoice';b.dataset.src=assetUrl('assets/photos/'+file);b.title=title;const img=document.createElement('img');img.src=assetUrl('assets/photos/thumbs/'+file);img.alt=title;img.loading='lazy';const caption=document.createElement('span');caption.textContent=title;b.append(img,caption);b.addEventListener('click',()=>{setImageSource(b.dataset.src,{kind:'gallery',file,title});galleryDialog.close();});galleryGrid.appendChild(b);}}
function saveGameFile(){if(!geom||!pieces.length)return;const data=createSaveData({shape:shapeSelect.value,requestedPieces:Number(pieceCount.value),seed,board:{width:geom.boardWidth,height:geom.boardHeight},playfield,currentLayer,complete:gameComplete,image:currentImage,pieces}),blob=new Blob([stringifySaveData(data)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a'),stamp=new Date().toISOString().slice(0,10);a.href=url;a.download=`libre-jigsaw-${stamp}.ljf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0);setLoadStatus('puzzleSaved');}
function restoreSave(data){shapeSelect.value=data.shape;pieceCount.value=String(data.requestedPieces);savePref('shape',data.shape);savePref('pieces',data.requestedPieces);seed=data.seed>>>0;const legacy=data.formatVersion===1;playfield=legacy?{width:Math.max(1,canvas.clientWidth),height:Math.max(1,canvas.clientHeight)}:{width:data.playfield.width,height:data.playfield.height};geom=legacy?createGeometryForPlayfield():createGeometryForBoard(data.board.width,data.board.height);rebuildImage();if(geom.tiles.length!==data.pieces.length)throw new Error('piece count mismatch');const sx=legacy?geom.boardWidth/data.board.width:1,sy=legacy?geom.boardHeight/data.board.height:1,byIndex=new Map(geom.tiles.map(t=>[t.index,t]));pieces=data.pieces.map(s=>{const t=byIndex.get(s.index);if(!t)throw new Error('piece index mismatch');return{...t,x:s.x*sx,y:s.y*sy,rotation:((s.rotation%geom.rotationSteps)+geom.rotationSteps)%geom.rotationSteps,group:s.group,z:s.z,layer:s.layer};});pieces.sort((a,b)=>a.z-b.z);pieces.forEach((p,i)=>p.z=i);currentLayer=data.currentLayer;layerSelect.value=String(currentLayer);selectedGroups.clear();drag=null;gameComplete=false;complete.classList.add('hidden');updateViewport();if(data.complete&&pieces.length){const groups=new Set(pieces.map(p=>p.group));if(groups.size!==1)throw new Error('invalid completed groups');finishGame(pieces[0].group);}else draw();setLoadStatus('puzzleLoaded');}
function loadSavedGame(file){if(!file)return;setLoadStatus('loadingPuzzle');const reader=new FileReader();reader.onerror=()=>setLoadStatus('saveLoadError');reader.onload=()=>{let data;try{data=parseSaveText(String(reader.result));}catch(e){setLoadStatus(e?.code==='LEGACY_LJF'?'legacySaveUnsupported':'saveLoadError');return;}let src,meta;if(data.image.kind==='gallery'){const known=PHOTOS.find(([f])=>f===data.image.file);if(!known){setLoadStatus('saveLoadError');return;}meta={kind:'gallery',file:known[0],title:known[1]};src=assetUrl('assets/photos/'+known[0]);}else{meta={kind:'embedded',name:data.image.name||'image',mime:data.image.mime||'image/*',data:data.image.data};src=data.image.data;}setImageSource(src,meta,()=>restoreSave(data));};reader.readAsText(file);}

canvas.addEventListener('pointerdown',e=>{if(gameComplete||e.button!==0)return;canvas.focus();const p=pos(e),piece=hit(p.x,p.y);if(piece){if(selectedGroups.size&&selectedGroups.has(piece.group)){bringGroupsTop(selectedGroups);drag={mode:'selection',groups:new Set(selectedGroups),start:p,last:p,moved:false,pointerId:e.pointerId};}else{if(selectedGroups.size)clearSelection();bringGroupTop(piece.group);drag={mode:'group',piece,group:piece.group,start:p,last:p,moved:false,pointerId:e.pointerId};}}else{if(selectedGroups.size)clearSelection();drag={mode:'marquee',start:p,last:p,moved:false,pointerId:e.pointerId};}canvas.setPointerCapture(e.pointerId);draw();});
canvas.addEventListener('pointermove',e=>{if(gameComplete||!drag||e.pointerId!==drag.pointerId)return;const p=pos(e),dx=p.x-drag.last.x,dy=p.y-drag.last.y;if(Math.hypot(p.x-drag.start.x,p.y-drag.start.y)>4)drag.moved=true;if(drag.mode==='group')moveGroup(drag.group,dx,dy);else if(drag.mode==='selection')moveGroups(drag.groups,dx,dy);drag.last=p;draw();});
canvas.addEventListener('pointerup',e=>{if(gameComplete||!drag||e.pointerId!==drag.pointerId)return;const d=drag;drag=null;if(d.mode==='group'){if(d.moved)trySnap(d.group);else rotateGroup(d.piece,-1);}else if(d.mode==='marquee'&&d.moved){setSelection(normalizeRect(d.start,d.last));}draw();});
canvas.addEventListener('pointercancel',()=>{drag=null;draw();});
canvas.addEventListener('contextmenu',e=>{e.preventDefault();if(gameComplete)return;const p=pos(e),piece=hit(p.x,p.y);if(!piece)return;if(selectedGroups.size&&selectedGroups.has(piece.group))return;if(selectedGroups.size)clearSelection();bringGroupTop(piece.group);rotateGroup(piece,1);trySnap(piece.group);});
canvas.addEventListener('keydown',e=>{if(gameComplete)return;if(e.key==='1'||e.key==='2'||e.key==='3'){e.preventDefault();switchLayer(Number(e.key)-1);return;}if(!drag||drag.mode!=='group')return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();rotateGroup(drag.piece,e.key==='ArrowLeft'?-1:1);drag.group=drag.piece.group;}});
const toolbarMenus=[...document.querySelectorAll('.toolbarMenu')];
function closeToolbarMenus(except=null){for(const m of toolbarMenus)if(m!==except)m.removeAttribute('open');}
for(const menu of toolbarMenus)menu.addEventListener('toggle',()=>{if(menu.open)closeToolbarMenus(menu);});
document.addEventListener('pointerdown',e=>{if(!e.target.closest('.toolbarMenu'))closeToolbarMenus();});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeToolbarMenus();});
newBtn.addEventListener('click',()=>{newGame(true);closeToolbarMenus();});
saveBtn.addEventListener('click',()=>{saveGameFile();closeToolbarMenus();});
saveInput.addEventListener('click',()=>{saveInput.value='';});
saveInput.addEventListener('change',()=>{loadSavedGame(saveInput.files?.[0]);closeToolbarMenus();});
galleryBtn.addEventListener('click',()=>{closeToolbarMenus();galleryDialog.showModal();});
pieceCount.addEventListener('change',()=>{savePref('pieces',pieceCount.value);newGame(true);closeToolbarMenus()});
shapeSelect.addEventListener('change',()=>{savePref('shape',shapeSelect.value);newGame(true);closeToolbarMenus()});
layerSelect.addEventListener('change',()=>{switchLayer(layerSelect.value);closeToolbarMenus();});
imageInput.addEventListener('click',()=>{imageInput.value='';});
imageInput.addEventListener('change',()=>{loadUserImage(imageInput.files?.[0]);closeToolbarMenus();});
langBtn.addEventListener('click',()=>{lang=lang==='en'?'it':'en';savePref('lang',lang);applyLanguage(lang);langBtn.textContent=lang==='en'?'IT':'EN';if(loadStatus?.dataset.statusKey)setLoadStatus(loadStatus.dataset.statusKey);});
for(const[b,d]of[['helpBtn','helpDialog'],['creditsBtn','creditsDialog']])document.querySelector('#'+b).addEventListener('click',()=>{closeToolbarMenus();document.querySelector('#'+d).showModal();});
document.querySelectorAll('dialog .close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
const storedShape=readPref('shape','square'),storedPieces=readPref('pieces','24');if(['square','hex'].includes(storedShape))shapeSelect.value=storedShape;if(['12','24','48','96'].includes(storedPieces))pieceCount.value=storedPieces;layerSelect.value='0';
buildGallery();applyLanguage(lang);langBtn.textContent=lang==='en'?'IT':'EN';image.onload=()=>newGame(true);image.onerror=()=>setLoadStatus('imageLoadError');image.src=imageURL;window.addEventListener('resize',resize);resize();
