// GPL-3.0-or-later. Clean JavaScript port of Jonathan Hulka's 2011/2012
// JigsawCutter + SquareJigsawManager + HexJigsawManager geometry.
// See specs/ARCHAEOLOGY.md.
const TAU=Math.PI*2;
export function makeRng(seed){let s=(seed>>>0)||0x6d2b79f5;return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
const ri=(rng,n)=>Math.floor(rng()*n);
const trunc=n=>n<0?Math.ceil(n):Math.floor(n);
function rotatePoint(p,angle,cx,cy){const c=Math.cos(angle),s=Math.sin(angle),x=p.x-cx,y=p.y-cy;return{x:cx+x*c-y*s,y:cy+x*s+y*c};}
function edgeCurve(corners,controls,i,a,b,cp,bubbleSize,bubbleDirection){
 const direction=b.x-a.x>0?1:-1,midY=(a.y+b.y)/2,midX=cp,cpStemY1=a.y*.65+b.y*.35,cpStemY2=b.y*.65+a.y*.35,bubbleY=bubbleDirection*bubbleSize+midY,temp=direction*Math.abs(bubbleY-midY)/Math.sqrt(3),cpBubbleX1=midX-temp,cpBubbleX2=midX+temp,stemX1=cpBubbleX1*.25+midX*.75,stemX2=cpBubbleX2*.25+midX*.75,stemY1=bubbleY*.25+cpStemY1*.75,stemY2=bubbleY*.25+cpStemY2*.75;
 controls[i*6]={x:cp*.6+a.x*.4,y:a.y};controls[i*6+1]={x:midX,y:cpStemY1};corners[i*4+1]={x:stemX1,y:stemY1};controls[i*6+2]={x:cpBubbleX1,y:bubbleY};corners[i*4+2]={x:midX,y:bubbleY};controls[i*6+3]={x:cpBubbleX2,y:bubbleY};corners[i*4+3]={x:stemX2,y:stemY2};controls[i*6+4]={x:midX,y:cpStemY2};controls[i*6+5]={x:cp*.6+b.x*.4,y:b.y};
}
function renderPath(sideCount,corners,controls){const p=new Path2D();p.moveTo(corners[0].x,corners[0].y);for(let i=0;i<sideCount;i++){p.bezierCurveTo(controls[i*6].x,controls[i*6].y,controls[i*6+1].x,controls[i*6+1].y,corners[i*4+1].x,corners[i*4+1].y);p.quadraticCurveTo(controls[i*6+2].x,controls[i*6+2].y,corners[i*4+2].x,corners[i*4+2].y);p.quadraticCurveTo(controls[i*6+3].x,controls[i*6+3].y,corners[i*4+3].x,corners[i*4+3].y);p.bezierCurveTo(controls[i*6+4].x,controls[i*6+4].y,controls[i*6+5].x,controls[i*6+5].y,corners[((i+1)%sideCount)*4].x,corners[((i+1)%sideCount)*4].y);}p.closePath();return p;}

export function squareBestFit(width,height,count){let across=Math.floor(Math.sqrt(count*width/height))-1,down=0,total=0;while(total<count){across++;const tH=Math.floor(width/across);down=Math.max(1,Math.floor((height+tH/2)/tH));total=across*down;}return{across,down,total};}
export function createSquareGeometry(boardWidth,boardHeight,targetCount,seed){
 const fit=squareBestFit(boardWidth,boardHeight,targetCount),cols=fit.across,rows=fit.down;
 const cornerVarianceFactor=.12,bubbleMinFactor=.30,bubbleMaxFactor=.40,controlPointVarianceFactor=.05;
 let tw=Math.floor((boardWidth+boardHeight)/(cols+rows));const maxTW=Math.floor(boardWidth/(cols-2*cornerVarianceFactor)),maxTH=Math.floor(boardHeight/(rows-2*cornerVarianceFactor));tw=Math.min(tw,maxTW,maxTH);
 const th=tw,spacingX=tw,spacingY=tw,cornerVariance=Math.max(1,Math.floor(tw*cornerVarianceFactor)),controlVariance=Math.floor(tw*controlPointVarianceFactor),bubbleMin=Math.floor((tw-cornerVariance*2)*bubbleMinFactor),bubbleMax=Math.max(bubbleMin+1,Math.floor((tw-cornerVariance*2)*bubbleMaxFactor));
 const leftOffset=Math.floor((boardWidth-cols*spacingX-tw+spacingX)/2),topOffset=Math.floor((boardHeight-rows*spacingY-th+spacingY)/2),rightOffset=boardWidth-leftOffset-tw*cols,bottomOffset=boardHeight-topOffset-th*rows;
 const topVariance=Math.min(cornerVariance,topOffset),bottomVariance=Math.min(cornerVariance,bottomOffset),leftVariance=Math.min(cornerVariance,leftOffset),rightVariance=Math.min(cornerVariance,rightOffset),rng=makeRng(seed),data=new Map(),key=(x,y)=>`${x},${y}`;
 for(let y=-1;y<=rows;y++)for(let x=-1;x<=cols;x++){const d={cornerX:ri(rng,cornerVariance*2-1)-cornerVariance+1,cornerY:ri(rng,cornerVariance*2-1)-cornerVariance+1,bubble:[0,0],dir:[0,0],cp:[0,0]};for(let k=0;k<2;k++){d.bubble[k]=ri(rng,bubbleMax-bubbleMin)+bubbleMin;d.dir[k]=ri(rng,2)*2-1;d.cp[k]=controlVariance===0?0:ri(rng,controlVariance*2-1)-controlVariance+1;}if(x===-1||x===cols-1){d.bubble[1]=0;d.cp[1]=0;}if(y===0||y===rows){d.bubble[0]=0;d.cp[0]=0;}data.set(key(x,y),d);}
 for(let y=-1;y<=rows;y++){data.get(key(0,y)).cornerX=-leftVariance;data.get(key(cols,y)).cornerX=rightVariance;}for(let x=-1;x<=cols;x++){data.get(key(x,0)).cornerY=-topVariance;data.get(key(x,rows)).cornerY=bottomVariance;}
 const mask=[{x:0,y:0},{x:tw,y:0},{x:tw,y:th},{x:0,y:th}],center={x:tw/2,y:th/2};
 function cornerOwner(x,y,i){return i===0?[x,y]:i===1?[x+1,y]:i===2?[x+1,y+1]:[x,y+1];}
 function buildPath(x,y){const corners=new Array(16),controls=new Array(24);for(let i=0;i<4;i++){const [ox,oy]=cornerOwner(x,y,i),d=data.get(key(ox,oy));corners[i*4]={x:mask[i].x+d.cornerX,y:mask[i].y+d.cornerY};}for(let i=0;i<4;i++){const topIndex=i%2;let ex=x,ey=y;if(i===2)ey=y+1;else if(i===3)ex=x-1;const d=data.get(key(ex,ey)),theta=topIndex*Math.PI/2,a=rotatePoint(corners[i*4],-theta,center.x,center.y),b=rotatePoint(corners[((i+1)%4)*4],-theta,center.x,center.y);if(d.bubble[topIndex]===0&&d.cp[topIndex]===0){for(let j=0;j<6;j++)controls[i*6+j]={...b};for(let j=1;j<4;j++)corners[i*4+j]={...b};}else edgeCurve(corners,controls,i,a,b,(a.x+b.x)/2+d.cp[topIndex],d.bubble[topIndex],d.dir[topIndex]);for(let j=0;j<6;j++)controls[i*6+j]=rotatePoint(controls[i*6+j],theta,center.x,center.y);for(let j=1;j<4;j++)corners[i*4+j]=rotatePoint(corners[i*4+j],theta,center.x,center.y);}return renderPath(4,corners,controls);}
 const tiles=[];for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const index=y*cols+x;tiles.push({index,gx:x,gy:y,origX:leftOffset+x*spacingX,origY:topOffset+y*spacingY,path:buildPath(x,y)});}
 return{shape:'square',era:'2012',algorithm:'Libre Jigsaw 2012 JigsawCutter',cols,rows,tileCount:tiles.length,tileWidth:tw,tileHeight:th,spacingX,spacingY,leftOffset,topOffset,rotationSteps:4,tiles,parameters:{bubbleMinFactor,bubbleMaxFactor,controlPointVarianceFactor,cornerVarianceFactor}};
}

export function hexBestFit(width,height,count){let across=Math.floor(Math.sqrt(count*width/height))*2-1,down=0,total=0;while(total<count){across+=1;const tW=Math.floor(2*width/(across-1)),tH=Math.floor(tW*2/Math.sqrt(3)),vUnit=Math.max(1,Math.floor(tH/4)),vUnits=Math.floor((height+Math.floor(vUnit/2))/vUnit);down=Math.floor((vUnits+1)/3);total=Math.floor((across+1)/2)*Math.floor((down+1)/2)+Math.floor(across/2)*Math.floor(down/2);}return{across,down,total};}
const HEX_NEIGHBORS=[[1,-1],[2,0],[1,1],[-1,1],[-2,0],[-1,-1]];
export function createHexGeometry(boardWidth,boardHeight,targetCount,seed){
 const fit=hexBestFit(boardWidth,boardHeight,targetCount),cols=fit.across,rows=fit.down,sqrt3=Math.sqrt(3),cornerVarianceFactor=.10,bubbleMinFactor=.20,bubbleMaxFactor=.25,controlPointVarianceFactor=.05;
 let tW=Math.floor(2*boardWidth/(cols-1)),tH=4*Math.floor(boardHeight/(rows*3-1)),tW2=Math.floor(tH*sqrt3/2),cv=Math.floor(Math.min(tW2,tW)*cornerVarianceFactor),maxTW=Math.floor(((boardWidth+2*cv)/(cols-1))*2),maxTH=Math.floor(((boardHeight+2*cv)/(rows*3-1))*4),maxTW2=Math.floor(maxTH*sqrt3/2);maxTW=Math.min(maxTW,maxTW2);tW=Math.floor(tW/2)+Math.floor(tH*sqrt3);tW=Math.min(tW,maxTW);tH=Math.floor(2*tW/sqrt3);tH-=tH%4;tW-=tW%2;
 const spacingX=Math.floor(tW/2),spacingY=Math.floor(tH*3/4),leftOffset=trunc((boardWidth-cols*spacingX-tW+spacingX)/2),topOffset=trunc((boardHeight-rows*spacingY-tH+spacingY)/2),controlVariance=Math.floor(tW*controlPointVarianceFactor),cornerVariance=Math.max(1,Math.floor(tW*cornerVarianceFactor)),bubbleMin=Math.floor((tW-cornerVariance*2)*bubbleMinFactor),bubbleMax=Math.max(bubbleMin+1,Math.floor((tW-cornerVariance*2)*bubbleMaxFactor));
 const calcTop=topOffset+Math.floor(tH/4),calcBottom=boardHeight-calcTop-Math.floor((rows*3-1)*tH/4),calcLeft=leftOffset+Math.floor(tW/2),calcRight=boardWidth-calcLeft-Math.floor((cols-1)*tW/2),topVariance=Math.min(cornerVariance,calcTop),bottomVariance=Math.min(cornerVariance,calcBottom),leftVariance=Math.min(cornerVariance,calcLeft),rightVariance=Math.min(cornerVariance,calcRight),midX=Math.floor(tW/2),clipY=Math.floor(tH/4),rng=makeRng(seed),data=new Map(),key=(x,y)=>`${x},${y}`;
 for(let y=-1;y<=rows;y++)for(let x=-2;x<=cols;x++)if((x+y)%2===0){const d={cornerX:[0,0],cornerY:[0,0],bubble:[0,0,0],dir:[0,0,0],cp:[0,0,0]};for(let k=0;k<2;k++){d.cornerX[k]=ri(rng,cornerVariance*2-1)-cornerVariance+1;d.cornerY[k]=ri(rng,cornerVariance*2-1)-cornerVariance+1;}for(let k=0;k<3;k++){d.bubble[k]=ri(rng,bubbleMax-bubbleMin)+bubbleMin;d.dir[k]=ri(rng,2)*2-1;d.cp[k]=controlVariance===0?0:ri(rng,controlVariance*2-1)-controlVariance+1;}
   if(x===-2){d.bubble[1]=0;d.cp[1]=0;}else if(x===-1){for(let k=0;k<2;k++)d.cornerX[k]=midX-leftVariance;for(let k=0;k<3;k++){d.bubble[k]=0;d.cp[k]=0;}}else if(x===0){for(let k=0;k<2;k++)d.cornerX[k]=-leftVariance;}else if(x===cols-2){d.bubble[1]=0;d.cp[1]=0;}else if(x===cols-1){for(let k=0;k<2;k++)d.cornerX[k]=rightVariance;for(let k=0;k<3;k++){d.bubble[k]=0;d.cp[k]=0;}}else if(x===cols){for(let k=0;k<2;k++)d.cornerX[k]=rightVariance-midX;}
   if(y===-1){d.cornerY[1]=-topVariance;d.bubble[2]=0;d.cp[2]=0;}else if(y===0){d.cornerY[0]=clipY-topVariance;d.bubble[0]=0;d.cp[0]=0;}else if(y===rows-1){d.cornerY[1]=bottomVariance-clipY;d.bubble[2]=0;d.cp[2]=0;}else if(y===rows){d.cornerY[0]=bottomVariance;d.bubble[0]=0;d.cp[0]=0;}
   data.set(key(x,y),d);
 }
 const mask=[{x:tW/2,y:0},{x:tW,y:tH/4},{x:tW,y:tH*3/4},{x:tW/2,y:tH},{x:0,y:tH*3/4},{x:0,y:tH/4}],center={x:tW/2,y:tH/2},cornerOwner=[[0,0],[1,-1],[1,1],[0,0],[-1,1],[-1,-1]],cornerIndex=[0,1,0,1,0,1],edgeOwner=[[0,0],[0,0],[0,0],[-1,1],[-2,0],[-1,-1]];
 function buildPath(x,y){const corners=new Array(24),controls=new Array(36);for(let i=0;i<6;i++){const [dx,dy]=cornerOwner[i],d=data.get(key(x+dx,y+dy)),ci=cornerIndex[i];if(!d)throw new Error(`missing hex corner owner ${x+dx},${y+dy}`);corners[i*4]={x:mask[i].x+d.cornerX[ci],y:mask[i].y+d.cornerY[ci]};}for(let i=0;i<6;i++){const topIndex=i%3,[dx,dy]=edgeOwner[i],d=data.get(key(x+dx,y+dy));if(!d)throw new Error(`missing hex edge owner ${x+dx},${y+dy}`);const theta=Math.PI/6+topIndex*TAU/6,a=rotatePoint(corners[i*4],-theta,center.x,center.y),b=rotatePoint(corners[((i+1)%6)*4],-theta,center.x,center.y);if(d.bubble[topIndex]===0&&d.cp[topIndex]===0){for(let j=0;j<6;j++)controls[i*6+j]={...b};for(let j=1;j<4;j++)corners[i*4+j]={...b};}else edgeCurve(corners,controls,i,a,b,(a.x+b.x)/2+d.cp[topIndex],d.bubble[topIndex],d.dir[topIndex]);for(let j=0;j<6;j++)controls[i*6+j]=rotatePoint(controls[i*6+j],theta,center.x,center.y);for(let j=1;j<4;j++)corners[i*4+j]=rotatePoint(corners[i*4+j],theta,center.x,center.y);}return renderPath(6,corners,controls);}
 const tiles=[];for(let y=0;y<rows;y++)for(let x=0;x<cols;x++)if((x+y)%2===0){const index=tiles.length;tiles.push({index,gx:x,gy:y,origX:leftOffset+x*spacingX,origY:topOffset+y*spacingY,path:buildPath(x,y)});}
 return{shape:'hex',cols,rows,tileCount:tiles.length,tileWidth:tW,tileHeight:tH,spacingX,spacingY,leftOffset,topOffset,rotationSteps:6,neighborOffsets:HEX_NEIGHBORS,tiles};
}

export function rotateVectorSteps(x,y,steps,totalSteps){const a=steps*TAU/totalSteps,c=Math.cos(a),s=Math.sin(a);return{x:x*c-y*s,y:x*s+y*c};}
export function rotateVector(x,y,steps){const v=rotateVectorSteps(x,y,steps,4);return{x:Math.round(v.x),y:Math.round(v.y)};}
export function areGridNeighbors(a,b,shape){const dx=b.gx-a.gx,dy=b.gy-a.gy;if(shape==='hex')return HEX_NEIGHBORS.some(([x,y])=>x===dx&&y===dy)?{dx,dy}:null;return Math.abs(dx)+Math.abs(dy)===1?{dx,dy}:null;}
